url: http://regatasolarbalears.github.io
baseurl:

# Site settings
title: Regata Solar Baleares
email: makespace.mallorca@gmail.com
description: Competición de embarcaciones no tripuladas impulsadas por energía solar.

# Team names, titles and social links
people:

  - name: Makespace Mallorca
    social:
      - title: twitter
        url: https://twitter.com/MakespacePMI
      - title: github
        url: https://github.com/Makespace-Mallorca

  - name: Fablab Mallorca
    social:
      - title: twitter
        url: https://twitter.com/FablabMallorca

  - name: Museu Marítim de Mallorca
    social:
      - title: twitter
        url: https://twitter.com/MaritimMallorca

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  - content

# Menu
menu:
  - donde_cuando
  - talleres_tutoriales
  - participacion
  - patrocinadores
  - organizadores
